on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest
          clj-kondo: latest


      - name: Lint
        run: bin/lint

      - name: Run tests
        run: bin/test
